<?php

namespace App\Policies;

use App\Models\Pac;
use App\Models\User;

/**
 * PAC = Plan d'Amélioration Continue (header). Generated by RH /
 * référent qualité (pac.generate). Updates by anyone with pac.update;
 * close by pac.close. View open to anyone with audits.view since PACs
 * are operational artifacts the whole quality team sees.
 */
class PacPolicy extends BasePolicy
{
    public function viewAny(User $user): bool
    {
        return $user->hasPermissionTo('audits.view');
    }

    public function view(User $user, Pac $pac): bool
    {
        return $user->hasPermissionTo('audits.view');
    }

    public function create(User $user): bool
    {
        return $user->hasPermissionTo('pac.generate');
    }

    public function update(User $user, Pac $pac): bool
    {
        return $user->hasPermissionTo('pac.update');
    }

    public function close(User $user, Pac $pac): bool
    {
        return $user->hasPermissionTo('pac.close');
    }

    public function delete(User $user, Pac $pac): bool
    {
        return $user->hasPermissionTo('pac.update');
    }
}
