<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Attempt to enable the three Postgres extensions we *would* like to have
 * available on the cluster. None of them are load-bearing at the application
 * layer:
 *
 *   - uuid-ossp / pgcrypto:  UUIDs are generated by Laravel's HasUuids trait
 *     in PHP (Str::uuid()), never by Postgres. Encryption uses Laravel's
 *     `encrypted` cast (APP_KEY in PHP), not pgcrypto.
 *   - pg_trgm:               powers the Cmd+K fuzzy search; the search code
 *     already falls back to plain LIKE when the operator `%` is unavailable.
 *
 * That means a shared-hosting Postgres without `postgresql-contrib` installed
 * can still run the application — just without similarity ranking.
 *
 * We log a warning per missing extension so the operator notices, but the
 * migration succeeds. Otherwise `php artisan migrate` would refuse to deploy
 * on any host where the contrib package is absent (typical of Hostinger,
 * many shared cPanel Postgres instances, etc.).
 */
return new class extends Migration
{
    public function up(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            return;
        }

        foreach (['uuid-ossp', 'pgcrypto', 'pg_trgm'] as $extension) {
            $this->tryEnable($extension);
        }
    }

    public function down(): void
    {
        if (DB::connection()->getDriverName() !== 'pgsql') {
            return;
        }

        foreach (['pg_trgm', 'pgcrypto', 'uuid-ossp'] as $extension) {
            try {
                DB::statement('DROP EXTENSION IF EXISTS "'.$extension.'"');
            } catch (Throwable) {
                // Best-effort cleanup — never block a rollback on a missing
                // extension.
            }
        }
    }

    private function tryEnable(string $extension): void
    {
        try {
            DB::statement('CREATE EXTENSION IF NOT EXISTS "'.$extension.'"');
        } catch (Throwable $e) {
            // `uuid-ossp` is in the postgresql-contrib package; shared
            // hosting Postgres instances frequently ship without it.
            // Log a warning and continue — the application still runs.
            Log::warning('Postgres extension unavailable, continuing without it.', [
                'extension' => $extension,
                'error' => $e->getMessage(),
                'impact' => match ($extension) {
                    'pg_trgm' => 'Cmd+K search will fall back to substring LIKE; no similarity ranking.',
                    default => 'None — Laravel generates UUIDs and ciphertext in PHP.',
                },
            ]);
        }
    }
};
